sonar.projectKey=chat_app_backend_treatment
sonar.sources=app/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/venv/**